include theos/makefiles/common.mk

APPLICATION_NAME = pebbletextios
pebbletextios_FILES = main.m pebbletextiosApplication.mm RootViewController.mm
pebbletextios_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
